# Generated by Django 5.0.7 on 2025-02-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vuelo",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Nacional", "Nacional"),
                            ("Internacional", "Internacional"),
                        ],
                        max_length=13,
                    ),
                ),
                ("Precio", models.IntegerField()),
            ],
        ),
    ]
